### ISSUE TITLE
Linked Library Source Code in Caller Contract Issue

### ISSUE THREAD

**Issue by Hellobloc** [blockscout/blockscout-rs#532]
# Intro
Only the function headers in the linked library source code in the caller contract are source-validated. This is because the linked library source code in the caller only affects the bytecode of the external delegatecall to the library, so the user can arbitrarily modify the linked library source code to defraud the user.
# Attack Case
For example, there is no self-destruct method in the source code of the following contract, but the contract still self-destructs.
https://optimism-goerli.blockscout.com/address/0x4fdaCE0cDb4eb9fd102df757808Ae6d83cF8af15?tab=contract
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/9060f967-4c57-4a23-98e5-a7485a0b01fb)
![image](https://github.com/blockscout/blockscout-rs/assets/113746997/0dabf6d5-49e0-48b7-a17b-c906c57dee23)

**Comment by rimrakhimov** [comment]
I'm not quite sure if that is really a vulnerability we can (and need to fix). In my opinion, it's better to consider the library source code more like an interface instead of as an actual source code. At least it seems to be much easier, as recursive library verification may be quite complicated. 

I agree, though, that it is not good idea to leave it as it is right now. What we've discussed internally is to show the user some side note (saying something like: "The linked library's source code may not be the real one. Check the source code at the library address (if any) if you want to be sure") in case if there is any library linked.

Or am I missing something and you've had some ideas regarding that issue?

**Comment by Hellobloc** [comment]
I think it would be nice to have a note as you mentioned at the end 👍 , I also reported this issue to etherscan a long time ago, but theirs also had the same opinion that it is not the responsibility of the verifier and that the user should check this issue themselves.

This is not an implementation problem, it is a common problem like reinit, and there have been a few attack cases.  So I think I need to report it and let's understand the issue together.

**Comment by rimrakhimov** [comment]
I see. Yeap, that sounds to be quite an issue, considering that there is no indication that the provided source code may not be the one fully corresponded to the contract. Honestly, I have never thought about such problem as well, even though I know how external and embedded libraries works. 

We will see how we can update our UI to make that clearer for the users. Thank you for pointing out on the problem! I'm not yet sure that we will be able mention you inside our release notes because our frontend repo is still closed. But will try to mention you in some way

**Comment by Hellobloc** [comment]
That's fantastic, thank you so much for mentioning me!

**Comment by tom2drum** [comment]
@Hellobloc here is a [demo](https://review-tom2drum-issue-975.k8s-dev.blockscout.com/address/0x4fdaCE0cDb4eb9fd102df757808Ae6d83cF8af15?tab=contract) how we are going to warn user about linked libraries. Please take a look and tell us what you think.
